import { Genre } from "../models/Genre";

export const GENRES: Genre[] = [
  { id: "all", name: "All" },
  { id: "pop", name: "Pop" },
  { id: "rock", name: "Rock" },
  { id: "hip-hop", name: "Hip-Hop" },
  { id: "electronic", name: "Electronic" },
  { id: "jazz", name: "Jazz" },
  { id: "classical", name: "Classical" },
  { id: "country", name: "Country" },
  { id: "reggae", name: "Reggae" },
  { id: "blues", name: "Blues" },
  { id: "metal", name: "Metal" },
  { id: "indie", name: "Indie" },
  { id: "r-n-b", name: "R&B" },
  { id: "latin", name: "Latin" },
  { id: "k-pop", name: "K-Pop" },
  { id: "edm", name: "EDM" },
  { id: "folk", name: "Folk" },
  { id: "soul", name: "Soul" },
  { id: "funk", name: "Funk" },
  { id: "punk", name: "Punk" },
  { id: "ambient", name: "Ambient" },
  { id: "disco", name: "Disco" },
  { id: "house", name: "House" },
  { id: "techno", name: "Techno" },
  { id: "trance", name: "Trance" },
  { id: "dubstep", name: "Dubstep" },
  { id: "reggaeton", name: "Reggaeton" },
  { id: "salsa", name: "Salsa" },
  { id: "bachata", name: "Bachata" },
  { id: "trap", name: "Trap" },
  { id: "grunge", name: "Grunge" },
  { id: "alternative", name: "Alternative" },
  { id: "synthwave", name: "Synthwave" },
  { id: "lo-fi", name: "Lo-Fi" },
  { id: "world-music", name: "World Music" },
  { id: "opera", name: "Opera" },
  { id: "gospel", name: "Gospel" },
  { id: "ska", name: "Ska" },
  { id: "hardcore", name: "Hardcore" },
  { id: "drum-and-bass", name: "Drum and Bass" },
];
